site:
  title: "Guilherme Segatto - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Guilherme Segatto"
  avatar: "https://www.github.com/guilhermesegattoo.png"
  socialNetworks:
    instagram: "https://www.instagram.com/segattooow"
    github: "https://www.github.com/guilhermesegattoo"
    linkedin: "https://www.linkedin.com/in/guilhermesegatto"
